### ISSUE TITLE
Are there exapmle tests are based on the auto-scaling algorithm of the service itself?

### ISSUE THREAD

**Issue by wang-mask** [cau-se/theodolite#19]
Hello, i am newbee for this project. 
May I ask if there exapmle tests are based on the auto-scaling algorithm of the service itself? Can I implement a scaling algorithm myself for testing?
And Does Apache Flink have supported the vertical scaling?
Thank you!

**Comment by SoerenHenning** [comment]
Hi, first sorry for late reply. I must have overlooked the notification of your issue.

Regarding your question, I am not sure whether there might be some confusion regarding the purpose of Theodolite. Theodolite is not a framework for auto-scaling an application at runtime based on the load on that application. Instead, it evaluates in multiple isolated experiments whether specified resource configurations can handle specified load intensities without violating specified SLOs. Theodolite derives a function describing how the required resources evolve with increasing load. A detailed description of Theodolite's underlying benchmarking method can be found in:

> Sören Henning and Wilhelm Hasselbring. “A Configurable Method for Benchmarking Scalability of Cloud-Native Applications”. In: Empirical Software Engineering 27. 2022. DOI: [10.1007/s10664-022-10162-1](https://doi.org/10.1007/s10664-022-10162-1).

In our Theodolite benchmarks for Flink, we support benchmarking how Flink's vertical scalability (i.e. how does the amount of required CPU/memory evolve with increasing load with a fixed number of replicas). For this, you have to set the `resourceType` to `TaskSlotsAndPodResources` in your execution as shown here:

```yaml
# ...
spec:
  benchmark: "example-benchmark"
  # ...
  resources:
    resourceType: TaskSlotsAndPodResources
  # ...
```

We have a recent publication with an associated replication package, which conducts such experiments:

> S. Henning and W. Hasselbring. “Benchmarking scalability of stream processing frameworks deployed as microservices in the cloud”. In: Journal of Systems and Software 208. 2024. DOI: [10.1016/j.jss.2023.111879](https://doi.org/10.1016/j.jss.2023.111879).

If you want to evaluate another dimension of resources, you have to [create a new benchmark](https://www.theodolite.rocks/creating-a-benchmark.html) (potentially by copy-pasting one of the existing Flink benchmarks, e.g. [UC2 Flink](https://github.com/cau-se/theodolite/blob/main/theodolite-benchmarks/definitions/uc2-flink/uc2-flink-benchmark-operator.yaml)). There you can define your own way to to scale resources. Likewise, you can also update the load dimension to scale and the necessary SLOs.

Lets me know, if you need further help.

**Comment by wang-mask** [comment]
Ok, i see ,thank you!
