### ISSUE TITLE
Problem installing via helm

### ISSUE THREAD

**Issue by guifabrin** [cau-se/theodolite#8]
Hi ;)

helm repository is trying to get the package from URL https://github.com/cau-se/theodolite/releases/download/v0.7.0/theodolite-0.7.0-copy.tgz and this URL is invalid.

A manual way to do this is:
```
   helm install theodolite https://github.com/cau-se/theodolite/releases/download/v0.7.0/theodolite-0.7.0.tgz --values ./values.yaml
```

Thanks for the theodolite benchmark!

**Comment by SoerenHenning** [comment]
Thanks for your report! It should be fixed with a3dab4fbdb6725b030fe4f66bd4665573c4d7f92. You probably need to run `helm repo update` first. Please let me know if you need any additional help with installing or using Theodolite.
